apiVersion: v1
data:
  AWS_REGION: dXMtZWFzdC0x
  AWS_SQS_URL: IltodHRwczovL3Nxcy51cy1lYXN0LTEuYW1hem9uYXdzLmNvbS85MDE5MTgxMTkyMDEvc3FzLXRlY2gtY2hhbGxlbmdlXShodHRwczovL3Nxcy51cy1lYXN0LTEuYW1hem9uYXdzLmNvbS85MDE5MTgxMTkyMDEvc3FzLXRlY2gtY2hhbGxlbmdlKSI=
  FLAG_SERVICE_URL: aHR0cDovL2ZsYWctc2VydmljZS5mbGFnLXNlcnZpY2Uuc3ZjOjgwMDI=
  PORT: ODAwNA==
  REDIS_URL: cmVkaXNzOi8vYWRtOlRlc3RlMTIzKlRlc3RlMTIzKkByZWRpcy10ZWNoLWNoYWxsZW5nZS1vbGdnb3guc2VydmVybGVzcy51c2UxLmNhY2hlLmFtYXpvbmF3cy5jb206NjM3OQ==
  SERVICE_API_KEY: dG1fa2V5XzdhMmI5ZWE2MzhmYWViNzg0MGI0ODBjZmNmYjIzM2I0N2FmODM4MDUyN2ZlNmRlYTJmNjJmMTAzNDA0MGI3MmE=
  TARGETING_SERVICE_URL: aHR0cDovL3RhcmdldGluZy1zZXJ2aWNlLnRhcmdldGluZy1zZXJ2aWNlLnN2Yzo4MDAz
kind: Secret
metadata:
  name: evaluation-service-secrets
  namespace: evaluation-service
