apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: evaluation-service
  labels:
    app: evaluation-service
spec:
  type: ClusterIP
  selector:
    app: evaluation-service
  ports:
    - name: http
      port: 8004
      targetPort: 8004
      protocol: TCP