name: toggle-master
services:

  db_auth-service:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./auth-service/db:/docker-entrypoint-initdb.d
      - postgres_auth_data:/var/lib/postgresql
    networks:
      - database
    
    environment:
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}

  auth_service:
    image: auth-server:1.0
    restart: always
    ports: 
      - 8001:8001
    networks:
      - database
      - backend
    environment:
      DATABASE_URL: ${AUTH_SERVICE_DATABASE_URL}
      PORT: ${AUTH_SERVICE_PORT}
      MASTER_KEY: ${AUTH_SERVICE_MASTER_KEY}
    depends_on:
      db_auth-service:
        condition: service_started

  db_flags-service:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5433:5433
    volumes:
      - ./flag-service/db:/docker-entrypoint-initdb.d
      - postgres_flag_data:/var/lib/postgresql
    networks:
      - database

    environment:
      POSTGRES_PASSWORD: ${FLAG_SERVICE_POSTGRES_PASSWORD}

  flags_service:
    image: flag-service:2.0
    restart: always
    ports: 
      - 8002:8002
    networks:
      - database
      - backend
    environment:
      DATABASE_URL: ${FLAG_SERVICE_DATABASE_URL}
      PORT: ${FLAG_SERVICE_PORT}
      AUTH_SERVICE_URL: ${FLAG_SERVICE_AUTH_SERVICE_URL}
    depends_on:
      db_flags-service:
        condition: service_started

  db_targeting-service:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5434:5434
    volumes:
      - ./targeting-service/db:/docker-entrypoint-initdb.d
      - postgres_targeting_data:/var/lib/postgresql
    networks:
      - database

    environment:
      POSTGRES_PASSWORD: ${TARGETING_SERVICE_POSTGRES_PASSWORD}

  targeting_service:
    image: targeting_service:2.0
    restart: always
    ports: 
      - 8003:8003
    networks:
      - database
      - backend
    environment:
      DATABASE_URL: ${TARGETING_SERVICE_DATABASE_URL}
      PORT: ${TARGETING_SERVICE_PORT}
      AUTH_SERVICE_URL: ${TARGETING_SERVICE_AUTH_SERVICE_URL}
    depends_on:
      db_targeting-service:
        condition: service_started

  db_redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - database

  evaluation-service:
    image: evaluation-service:2.0
    restart: always
    ports: 
      - 8004:8004
    networks:
      - database
      - backend
    environment:
      REDIS_URL: ${EVALUATION_SERVICE_REDIS_URL}
      PORT: ${EVALUATION_SERVICE_PORT}
      FLAG_SERVICE_URL: ${EVALUATION_SERVICE_FLAG_SERVICE_URL}
      TARGETING_SERVICE_URL: ${EVALUATION_SERVICE_TARGETING_SERVICE_URL}
      SERVICE_API_KEY: ${EVALUATION_SERVICE_SERVICE_API_KEY}
      AWS_SQS_URL: ${EVALUATION_SERVICE_AWS_SQS_URL}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    depends_on:
      db_redis:
        condition: service_started

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "/home/lgentil/fiap-etapa-2/dynamodb/data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - database

  analytics_service:
    image: analytics-service:3.0
    restart: always
    ports: 
      - 8005:8005
    networks:
      - database
      - backend
    environment:
      PORT: ${ANALYTICS_PORT}
      AWS_SQS_URL: ${ANALYTICS_AWS_SQS_URL}
      AWS_DYNAMODB_TABLE: ${ANALYTICS_AWS_DYNAMODB_TABLE}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      DYNAMODB_ENDPOINT: ${ANALYTICS_AWS_DYNAMODB_URL}
    depends_on:
      dynamodb-local:
        condition: service_started

volumes:
  dynamodb:
  postgres_auth_data:
  postgres_flag_data:
  postgres_targeting_data:

networks:
  database:
    driver: bridge
  backend:
    driver: bridge
