apiVersion: v1
data:
  AWS_DYNAMODB_TABLE: VG9nZ2xlTWFzdGVyQW5hbHl0aWNz
  AWS_REGION: dXMtZWFzdC0x
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vOTAxOTE4MTE5MjAxL3Nxcy10ZWNoLWNoYWxsZW5nZQ==
  PORT: ODAwNQ==
kind: Secret
metadata:
  name: analytics-service-secrets
  namespace: analytics-service
