apiVersion: v1
data:
  AUTH_SERVICE_DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpUZXN0ZTEyMypAZGItYXV0aC1zZXJ2aWNlLTEuY3d1NW04ZG1rdHpxLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2F1dGhfZGI=
  AUTH_SERVICE_MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=
  AUTH_SERVICE_PORT: ODAwMQ==
kind: Secret
metadata:
  name: auth-service-secrets