apiVersion: v1
data:
  TARGETING_SERVICE_AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZS5hdXRoLXNlcnZpY2Uuc3ZjOjgwMDE=
  TARGETING_SERVICE_DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpUZXN0ZTEyMypAZGItdGFyZ2V0aW5nLXNlcnZpY2UtMS5jd3U1bThkbWt0enEudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvdGFyZ2V0aW5nX2Ri
  TARGETING_SERVICE_PORT: ODAwMw==
kind: Secret
metadata:
  name: targeting-service-secrets
  namespace: targeting-service
