apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: targeting-service
  labels:
    app: targeting-service
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP