apiVersion: v1
data:
  FLAG_SERVICE_AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZS5hdXRoLXNlcnZpY2Uuc3ZjOjgwMDE=
  FLAG_SERVICE_DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpUZXN0ZTEyMypAZGItZmxhZy1zZXJ2aWNlLTEuY3d1NW04ZG1rdHpxLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2ZsYWdzX2Ri
  FLAG_SERVICE_PORT: ODAwMg==
kind: Secret
metadata:
  name: flag-service-secrets
  namespace: flag-service
