apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: flag-service
  labels:
    app: flag-service
spec:
  type: ClusterIP
  selector:
    app: flag-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP